version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8000:8000
    depends_on: 
      - db

  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./database:/data/db
    # env_file: 
    #   - ./server/.env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      # - MONGO_INITDB_DATABASE=$${MONGODB_DATABASE}

volumes: 
  database: 