version: "3.9"
services:
  server:
    container_name: container-node
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8000:8000
    depends_on: 
      - db

  db:
    container_name: container-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MyPass123

  client:
    container_name: container-react
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
    restart: on-failure

