version: "3.9"
services:
  server:
    container_name: container-node-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8000:8000
    depends_on: 
      - db

  db:
    container_name: container-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MyPass123
