version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8000:8000"

  # postgres:
  #   image: postgres:12.7-alpine
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: 'admin'
  #     POSTGRES_PASSWORD: 'C0V1D19'
  #     POSTGRES_DB: 'wallet_production'